### Cross-Validation and the Bootstrap

In [4]:
 import numpy as np
 import statsmodels.api as sm
 from ISLP import load_data
 from ISLP.models import (ModelSpec as MS,
 summarize,
 poly)
 from sklearn.model_selection import train_test_split

In [6]:
 from functools import partial
 from sklearn.model_selection import \
 (cross_validate,
 KFold,
 ShuffleSplit)
 from sklearn.base import clone
 from ISLP.models import sklearn_sm


#### 1.The Validation Set Approch

In [11]:
 Auto = load_data('Auto')
 Auto_train, Auto_valid = train_test_split(Auto,
 test_size=196,
 random_state=0)

In [13]:
Auto

mpg  cylinders  displacement  horsepower  weight  \
name                                                                           
chevrolet chevelle malibu  18.0          8         307.0         130    3504   
buick skylark 320          15.0          8         350.0         165    3693   
plymouth satellite         18.0          8         318.0         150    3436   
amc rebel sst              16.0          8         304.0         150    3433   
ford torino                17.0          8         302.0         140    3449   
...                         ...        ...           ...         ...     ...   
ford mustang gl            27.0          4         140.0          86    2790   
vw pickup                  44.0          4          97.0          52    2130   
dodge rampage              32.0          4         135.0          84    2295   
ford ranger                28.0          4         120.0          79    2625   
chevy s-10                 31.0          4         119.0          82    2720   

                           acceleration  year  origin  
name                                                   
chevrolet chevelle malibu          12.0    70       1  
buick skylark 320                  11.5    70       1  
plymouth satellite                 11.0    70       1  
amc rebel sst                      12.0    70       1  
ford torino                        10.5    70       1  
...                                 ...   ...     ...  
ford mustang gl                    15.6    82       1  
vw pickup                          24.6    82       2  
dodge rampage                      11.6    82       1  
ford ranger                        18.6    82       1  
chevy s-10                         19.4    82       1  

[392 rows x 8 columns]

In [15]:
 hp_mm = MS(['horsepower'])
 X_train = hp_mm.fit_transform(Auto_train)
 y_train = Auto_train['mpg']
 model = sm.OLS(y_train, X_train)
 results = model.fit()

In [17]:
X_valid = hp_mm.transform(Auto_valid)
y_valid = Auto_valid['mpg']
valid_pred = results.predict(X_valid)
np.mean((y_valid- valid_pred)**2)

23.616617069669882

In [19]:
def evalMSE(terms,
 response,
 train,
 test):
 mm = MS(terms)
 X_train = mm.fit_transform(train)
 y_train = train[response]
 X_test = mm.transform(test)
 y_test = test[response]
 results = sm.OLS(y_train, X_train).fit()
 test_pred = results.predict(X_test)
 return np.mean((y_test- test_pred)**2)

In [23]:
 MSE = np.zeros(3)
 for idx, degree in enumerate(range(1, 4)):
     MSE[idx] = evalMSE([poly('horsepower', degree)],
                        'mpg',
                        Auto_train,
                        Auto_valid)
 MSE

array([23.61661707, 18.76303135, 18.79694163])

In [31]:
Auto_train, Auto_valid = train_test_split(Auto,
 test_size=196,
 random_state=3)
MSE = np.zeros(3)
for idx, degree in enumerate(range(1, 4)):
     MSE[idx] = evalMSE([poly('horsepower', degree)],
                        'mpg',
                        Auto_train,
                        Auto_valid)
MSE

array([20.75540796, 16.94510676, 16.97437833])

### 2. Cross-Validation

In [34]:
 hp_model = sklearn_sm(sm.OLS,
 MS(['horsepower']))
 X, Y = Auto.drop(columns=['mpg']), Auto['mpg']
 cv_results = cross_validate(hp_model,
 X,
 Y,
 cv=Auto.shape[0])
 cv_err = np.mean(cv_results['test_score'])
 cv_err

24.231513517929233

In [40]:
 cv_error = np.zeros(5)
 H = np.array(Auto['horsepower'])
 M = sklearn_sm(sm.OLS)
 for i, d in enumerate(range(1,6)):
     X = np.power.outer(H, np.arange(d+1))
     M_CV = cross_validate(M,
                           X,
                           Y,
 cv=Auto.shape[0])
 cv_error[i] = np.mean(M_CV['test_score'])
 cv_error

array([ 0.       ,  0.       ,  0.       ,  0.       , 19.0332262])

In [44]:
A = np.array([3, 5, 9])
B = np.array([2, 4])
np.add.outer(A, B)

array([[ 5,  7],
       [ 7,  9],
       [11, 13]])

In [48]:
 cv_error = np.zeros(5)
 cv = KFold(n_splits=10,
 shuffle=True,
 random_state=0) # use same splits for each degree
 for i, d in enumerate(range(1,6)):
     X = np.power.outer(H, np.arange(d+1))
     M_CV = cross_validate(M,
                           X,
                           Y,
                           cv=cv)
 cv_error[i] = np.mean(M_CV['test_score'])
 cv_error

array([ 0.        ,  0.        ,  0.        ,  0.        , 19.13719075])

In [52]:
validation = ShuffleSplit(n_splits=1,
test_size=196,
random_state=0)
results = cross_validate(hp_model,
Auto.drop(['mpg'], axis=1),
Auto['mpg'],
cv=validation);
results['test_score']

array([23.61661707])

### 3.The Bootstrap

In [62]:
Portfolio = load_data('Portfolio')
def alpha_func(D, idx):
    cov_ = np.cov(D[['X','Y']].loc[idx], rowvar=False)
    return ((cov_[1,1]- cov_[0,1]) /
            (cov_[0,0]+cov_[1,1]-2*cov_[0,1]))

In [64]:
alpha_func(Portfolio, range(100))

0.57583207459283

In [66]:
 rng = np.random.default_rng(0)
 alpha_func(Portfolio,
 rng.choice(100,
 100,
 replace=True))

0.6074452469619004

In [76]:
 def boot_SE(func,
 D,
 n=None,
 B=1000,
 seed=0):
     rng = np.random.default_rng(seed)
     first_, second_ = 0, 0
     n = n or D.shape[0]
     for _ in range(B):
         idx = rng.choice(D.index,
                      n,
                      replace=True)
         value = func(D, idx)
         first_ += value
         second_ += value**2
         return np.sqrt(second_ / B- (first_ / B)**2)

In [80]:
alpha_SE = boot_SE(alpha_func,
                   Portfolio,
                   B=1000,
                   seed=0)
alpha_SE

0.019199498387420112

In [84]:
 def boot_OLS(model_matrix, response, D, idx):
     D_ = D.loc[idx]
     Y_ = D_[response]
     X_ = clone(model_matrix).fit_transform(D_)
     return sm.OLS(Y_, X_).fit().params

In [86]:
hp_func = partial(boot_OLS, MS(['horsepower']), 'mpg')

In [96]:
rng = np.random.default_rng(0)
np.array([hp_func(Auto,
                  rng.choice(Auto.index, 392, replace=True)) for _ in range(10)])


array([[39.12226577, -0.1555926 ],
       [37.18648613, -0.13915813],
       [37.46989244, -0.14112749],
       [38.56723252, -0.14830116],
       [38.95495707, -0.15315141],
       [39.12563927, -0.15261044],
       [38.45763251, -0.14767251],
       [38.43372587, -0.15019447],
       [37.87581142, -0.1409544 ],
       [37.95949036, -0.1451333 ]])

In [100]:

 hp_se = boot_SE(hp_func,
 Auto,
 B=1000,
 seed=10)
 hp_se

intercept     1.270578
horsepower    0.005293
dtype: float64

In [102]:
 hp_model.fit(Auto, Auto['mpg'])
 model_se = summarize(hp_model.results_)['std err']
 model_se

intercept     0.717
horsepower    0.006
Name: std err, dtype: float64

In [104]:
 quad_model = MS([poly('horsepower', 2, raw=True)])
 quad_func = partial(boot_OLS,
 quad_model,
 'mpg')
 boot_SE(quad_func, Auto, B=1000)


intercept                                  1.702187
poly(horsepower, degree=2, raw=True)[0]    0.013427
poly(horsepower, degree=2, raw=True)[1]    0.000035
dtype: float64

In [106]:
 M = sm.OLS(Auto['mpg'],
 quad_model.fit_transform(Auto))
 summarize(M.fit())['std err']

intercept                                  1.800
poly(horsepower, degree=2, raw=True)[0]    0.031
poly(horsepower, degree=2, raw=True)[1]    0.000
Name: std err, dtype: float64