# Basic Commands

In [1]:
print('fit a model with', 11, 'variables')

fit a model with 11 variables


In [2]:
print?


Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

In [3]:
3 + 5


8

In [4]:
"hello" + " " + "world"

'hello world'

In [5]:
x = [3, 4, 5]
x

[3, 4, 5]

In [6]:
y = [4, 9, 7]
x + y

[3, 4, 5, 4, 9, 7]

# Introduction to Numerical Python

In [7]:
import numpy as np 

In [8]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [9]:
x + y

array([ 7, 13, 12])

In [10]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [11]:
x.ndim

2

In [12]:
x.dtype

dtype('int32')

In [13]:
np.array([[1, 2], [3.0, 4]]).dtype

dtype('float64')

In [14]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If true (default), then the object is copied.  Otherwise, a copy will
    only be made if ``__array__`` returns a copy, if obj is a nested
    sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.).
order : {'K', 'A', 'C', 'F'}, optional
    Specify the memory layout of the array. If object is not an array, the
    newly crea

In [15]:
np.array([[1, 2], [3, 4]], float).dtype

dtype('float64')

In [16]:
x.shape

(2, 2)

In [17]:
x = np.array([1, 2, 3, 4])
x.sum()

10

In [18]:
x = np.array([1, 2, 3, 4])
np.sum(x)

10

In [19]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape((2, 3))
print('reshaped x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reshaped x:
 [[1 2 3]
 [4 5 6]]


In [20]:
x_reshape[0, 0] 

1

In [21]:
x_reshape[1, 2] 

6

In [22]:
print('x before we modify x_reshape:\n', x)
print('x_reshape before we modify x_reshape:\n', x_reshape)
x_reshape[0, 0] = 5
print('x_reshape after we modify its top left element:\n', x_reshape)
print('x after we modify top left element of x_reshape:\n', x)

x before we modify x_reshape:
 [1 2 3 4 5 6]
x_reshape before we modify x_reshape:
 [[1 2 3]
 [4 5 6]]
x_reshape after we modify its top left element:
 [[5 2 3]
 [4 5 6]]
x after we modify top left element of x_reshape:
 [5 2 3 4 5 6]


In [23]:
my_tuple = (3, 4, 5)
my_tuple[0] = 2

TypeError: 'tuple' object does not support item assignment

In [24]:
x_reshape.shape, x_reshape.ndim, x_reshape.T

((2, 3),
 2,
 array([[5, 4],
        [2, 5],
        [3, 6]]))

In [25]:
np.sqrt(x)

array([2.23606798, 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])